In [1]:
action_dict = {0: ('pass', 'pass'),
                            1: ('sk1', 1),
                            2: ('sk2', 2),
                            3: ('sk3', 3)}

In [10]:
import random
import copy
used_skill_1 = 1
used_skill_2 = 0
used_skill_3 = 0

def get_random_action():
        action_dict_copy = copy.deepcopy(action_dict)
        if used_skill_1 == 1:
            del action_dict_copy[1]
        if used_skill_2 == 1:
            del action_dict_copy[2]
        if used_skill_3 == 1:
            del action_dict_copy[3]
        random_pass_list = [(0,('pass', 'pass'))*(int(1 * len(action_dict)))]
        return random.choice(list(action_dict_copy.items())+random_pass_list)
    
get_random_action()

(3, ('sk3', 3))

In [11]:
for i in range(10):
    print(get_random_action()[1])

('pass', 'pass')
('pass', 'pass')
('pass', 'pass')
('pass', 'pass')
('sk2', 2)
('sk2', 2)
('sk3', 3)
('pass', 'pass')
('pass', 'pass')
('sk3', 3)


In [5]:
random_pass_list = [(0,('pass', 'pass'))*(int(1 * len(action_dict)))]

In [6]:
random_pass_list

[(0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'))]

In [9]:
list(action_dict.items())+random_pass_list

[(0, ('pass', 'pass')),
 (1, ('sk1', 1)),
 (2, ('sk2', 2)),
 (3, ('sk3', 3)),
 (0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'),
  0,
  ('pass', 'pass'))]

In [1]:
import numpy as np
def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum

In [77]:
test = np.array([[0.55300971, 0.14902494, 0.14899144, 0.14897391]])

In [78]:
test

array([[0.55300971, 0.14902494, 0.14899144, 0.14897391]])

In [79]:
softmax(test)

array([[0.33301071, 0.22233603, 0.22232858, 0.22232468]])

In [80]:
zz = test

In [81]:
zz[0][1] = zz[0][0] +3

In [82]:
for i in zz[0]:
    print(i)
softmax(zz)

0.55300971
3.55300971
0.14899144
0.14897391


array([[0.04460146, 0.89584434, 0.02977736, 0.02977684]])

In [5]:
[i*100 for i in test[0]]

[55.300971, 14.902493999999999, 14.899144, 14.897390999999999]

In [10]:
softmax(np.array([[5.300971, 1.4902493999999999, 1.4899144, 1.4897390999999999]]))

array([[0.93775386, 0.02075456, 0.02074761, 0.02074397]])

In [9]:
softmax([.5,1])

array([0.37754067, 0.62245933])

In [21]:
# custom function
import math
def sigmoid(x):
    return 1/(1 + np.exp(-x)) 

zz = sigmoid(test)

In [22]:
for i in zz[0]:
    print(i)

0.6348335844214177
0.5371874375685064
0.537179108885466
0.5371747506141017


In [35]:
zz[0][0] = 3

In [36]:
zz

array([[3.        , 0.53718744, 0.53717911, 0.53717475]])

In [37]:
sigmoid(zz)

array([[0.95257413, 0.6311579 , 0.63115596, 0.63115495]])

In [38]:
softmax(np.array([[0.95257413, 0.6311579 , 0.63115596, 0.63115495]]))

array([[0.31492487, 0.22835875, 0.22835831, 0.22835808]])

In [1]:
card_indices = (2, 1, 0)
for card_index in card_indices:
    if card_index == 0:
        print('c1')
    elif card_index == 1:
        print('c2')
    elif card_index == 2:
        print('c3')
    elif card_index == 3:
        print('c4')
    elif card_index == 4:
        print('c5')

c3
c2
c1
