In [1]:
from heroic_spirt import HeroicSpirit, Chaldea
#from netlearner import DQNLearner
import numpy as np


#card types as classes
import itertools
from random import choice
from random import shuffle, randint
%load_ext autoreload
%autoreload 2

Using TensorFlow backend.
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarn

In [2]:
HeroicSpirit

heroic_spirt.HeroicSpirit

In [3]:
chaldea = Chaldea()

Instructions for updating:
Colocations handled automatically by placer.


/Users/msugimura/Documents/GitHub/multiagent_pendragon/fgo_environment/heroic_spirt.py:98: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(128, activation="relu", input_dim=20, kernel_initializer="glorot_normal")`
  model.add(Dense(128, init='glorot_normal', activation = 'relu', input_dim=self.feature_vector_len))
/Users/msugimura/Documents/GitHub/multiagent_pendragon/fgo_environment/heroic_spirt.py:100: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(128, activation="relu", kernel_initializer="glorot_normal")`
  model.add(Dense(128, init='glorot_normal', activation = 'relu'))
/Users/msugimura/Documents/GitHub/multiagent_pendragon/fgo_environment/heroic_spirt.py:101: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="relu", kernel_initializer="glorot_normal")`
  model.add(Dense(64, init='glorot_normal', activation = 'relu'))
/Users/msugimura/Documents/GitHub/multiagent_pendragon/fgo_environment/heroic_spirt.py:102: UserWar

In [4]:
chaldea.deck

[('hero1', 'quick'),
 ('hero1', 'arts'),
 ('hero1', 'arts'),
 ('hero1', 'buster'),
 ('hero1', 'buster'),
 ('hero2', 'quick'),
 ('hero2', 'arts'),
 ('hero2', 'arts'),
 ('hero2', 'buster'),
 ('hero2', 'buster'),
 ('hero3', 'quick'),
 ('hero3', 'arts'),
 ('hero3', 'arts'),
 ('hero3', 'buster'),
 ('hero3', 'buster')]

In [5]:
chaldea.hero1.skill_1()

{'name': 'sk1_hero1_jalter_self_modification_ex',
 'target': ['hero1'],
 'hp_boost': 0,
 'np_boost': 0.0,
 'critical_boost': 0.5,
 'critical_star_boost': 0.0,
 'dmg_boost': ('all', 0.0),
 'duration': 3}

In [6]:
def deal_hand(deck):
    shuffle(deck)
    final_deck = deck[:5]
    #print(final_deck)
    servant_numbers = [i[0] for i in final_deck] 
    card_deck = [i[1] for i in final_deck] 

    return card_deck, servant_numbers 

card_deck, servant_numbers  = deal_hand(chaldea.deck)


In [7]:

'''
first two classes track the player and enemy teams
'''
class team_chaldela:
    #hp is total team hitpoints
    #deck is the total 15 card deck of the team
    
    def __init__(self):
        self.hit_points = hp
        self.card_deck = card_deck
        self.np_charge = 0
        self.current_stars = 0

    def get_action(self, state =None):
        print('hi')

class enemy_servants:
    
    def __init__(self,hp,dmg_max):
        self.hit_points = hp
        self.dmg_max = dmg_max
    def deal_damage(self):
        return randint(1, self.dmg_max ) 
        

'''
way to shuffle 15 card deck and deal 5 cards.
for now cards are replaced. in FGO there is no replacement
and deck is remade every 3 turns
'''
#def deal_hand(deck):
#    shuffle(deck)
#    
#    return deck[:5] 
def deal_hand(deck):
    shuffle(deck)
    final_deck = deck[:5]
    print(final_deck)
    servant_numbers = [i[0] for i in final_deck] 
    card_deck = [i[1] for i in final_deck] 

    return card_deck, servant_numbers 
'''
Next 3 Classes track the cards and give their damage, NP gain, and stars 
that are created when they are played
'''
class Buster:
    def __init__(self, card_number):
        if card_number == 1:
            self.dmg = 1.5
            self.np_gain = 0
            self.stars = 1
            
        if card_number == 2:
            self.dmg = 1.8
            self.np_gain = 0
            self.stars = 2
            
        if card_number == 3:
            self.dmg = 2.1
            self.np_gain = 0
            self.stars = 3
            
class Arts:
    def __init__(self, card_number):
        if card_number == 1:
            self.dmg = 1.0
            self.np_gain = 4
            self.stars = 0
            
        if card_number == 2:
            self.dmg = 1.2
            self.np_gain = 5
            self.stars = 0
            
        if card_number == 3:
            self.dmg = 1.4
            self.np_gain = 6
            self.stars = 0
            
class Quick:
    def __init__(self, card_number):
        if card_number == 1:
            self.dmg = .8
            self.np_gain = 2
            self.stars = 4
            
        if card_number == 2:
            self.dmg = 0.96
            self.np_gain = 3
            self.stars = 6
            
        if card_number == 3:
            self.dmg = 1.12
            self.np_gain = 4
            self.stars = 8
'''
Next 5 functions are used in the calculate damage function which is the core 
part of the loop where the card choices by the player are translated into
damage, np gain, stars created, critical damage is calculated etc.
'''     
#using the input list which is just a list of strings of card types
# convert them into card objects which have stats and such
def command_card_gen(card_type,current_card_num):
    
    if card_type == 'buster':
        card = Buster(current_card_num)
    elif card_type == 'arts':
        card = Arts(current_card_num)
    elif card_type == 'quick':
        card = Quick(current_card_num)
    return card

#there is a bonus that gets applied based on the first card. 
# so check the first card and then we can apply the modifiers 
# in the rest of the cards
def first_card_mods(first_card):
    
    if first_card == 'buster':
        dmg_modifier = 1.5
        np_mod = 1.0
        star_mod = 1
        
    elif first_card == 'arts':
        dmg_modifier = 1.0
        np_mod = 2.0
        star_mod = 1
        
    elif first_card == 'quick':
        dmg_modifier = 1.0
        np_mod = 1.0
        star_mod = 1.2
    else:
        print('invalid command card')
    return dmg_modifier,np_mod,star_mod

'''
I am a fan of the DnD series called critical role so I couldnt resist
'''
def critical_role(team_obj):
    critical_chance = team_obj.current_stars*2
    critical_flip = randint(1,100)
    if critical_flip <=critical_chance:
        critical_mod = 2.0 + team_obj.critical_strength
        #print('')
    else:
        critical_mod = 1.0
    
    team_obj.current_stars = 0
    team_obj.critical_strength = 0
    return critical_mod
    
# combine the previous functions to calculate the damage output and whatnot 
# of a single chain

'''
core damage calculations, takes in a the card chain and outputs damage
also the team class object and the rewards for the round so appropriate 
adjustments can be made
'''
'''
function to pick the cards out of the dealt hand that the network selects
'''
def pick_cards(current_hand5,card_indexes = [0,1,2]):
    #cards can take on values of 0-4 and should be a list of ints
    #default is first 3 cards
    hand_to_play = []
    for i in card_indexes:
        hand_to_play.append(current_hand5[i])
    
    return hand_to_play

def picked_cards_servants(current_hand5,card_indexes = [0,1,2]):
    #cards can take on values of 0-4 and should be a list of ints
    #default is first 3 cards
    servants_list = []
    for i in card_indexes:
        servants_list.append(current_hand5[i])
    
    return servants_list
'''
used for testing, and 10% of the time cards are randomly selected
'''
def random_pick_cards():
    list1= list(itertools.permutations([0,1,2,3,4],3))
    hand = choice(list1)
    return hand 

'''
Function to check if a team is still alive
'''
def check_if_alive(team_instance):
    #if team's hp is higher than 0 than return true, 
    # false when one player drops to 0 or below
    if team_instance.hit_points >0:
        return 'alive'
    else:
        return 'dead'


In [8]:
enemy = enemy_servants(30,4)

In [9]:
enemy.deal_damage()

4

## HOW THE F TO ADD MULTIPLE AGENTS

so `player_team` might be able to manage HP. we can still keep the whole team as a giant punching bag??? that keeps the approach nice and simple in terms of doings stuff like having the enemies attack multiple times randomly angainst ppl... 

ISSUES: this means it will be hard to attribute what buffs do to what... like basically atm I am not doing card tracking so if merlin does a thing and buffs someone, the bots wont know to play buster cards... or even if they do a self buff for a specific type of card then that doesnt work well either... so basically... does this get solved by tagging each card with the owner... then factoring it into the damage calculations 

ISSUE 2 need to figure out how to apply individual NP damage since it is up to the bots when to use it? maybe??? who knows... or maybe just never give them access to the NP number since that is a feature

In [10]:

#This function contains some of the rewards. 
# At some point I actually listed as a reward of +2 which is actually
# higher than winning. it worked, but may be a break in accepted protocol
def card_chain_effect(cards_to_play,team_obj,round_reward):
    #print(cards_to_play)
    #takes command card chain (list), checks for chain, applies bonuses
    buster_chain_mod = 1
    
    if cards_to_play.count('buster') == 3:
        #print('buster chain!')
        buster_chain_mod = 1.2
        round_reward+=2
        #print('')
    elif cards_to_play.count('arts') == 3:
        
        team_obj.hero1.NP_charge +=20 
        team_obj.hero2.NP_charge +=20 
        team_obj.hero3.NP_charge +=20
        round_reward+=2
    elif cards_to_play.count('quick') == 3:
        team_obj.current_stars +=10 #this is still fine
        round_reward+=2
    else:
        #print('')
        #print('not a chain')
        buster_chain_mod = 1
    return buster_chain_mod, round_reward

def get_hero_damage_mods(team_obj,card_type,hero_number):
    dmg_mod = team_obj.hero_dict[hero_number].damage_mod_dict[card_type]
    
    return dmg_mod


def charge_hero_np(team_obj,hero_number,np_gain):
    if hero_number == 'hero1':
        team_obj.hero1.NP_charge +=np_gain
    elif hero_number == 'hero2':
        team_obj.hero2.NP_charge +=np_gain
    elif hero_number == 'hero3':
        team_obj.hero2.NP_charge +=np_gain
        
def use_NP(team_obj,total_damage):
    if team_obj.hero1.NP_charge >= 100:
        print(team_obj.hero1.name, 'used np')
        total_damage += team_obj.hero1.NP_damage
        team_obj.hero1.NP_charge = 0

    if team_obj.hero2.NP_charge >= 100:
        print(team_obj.hero2.name, 'used np')
        total_damage += team_obj.hero2.NP_damage
        team_obj.hero2.NP_charge = 0

    if team_obj.hero3.NP_charge >= 100:
        print(team_obj.hero3.name, 'used np')
        total_damage += team_obj.hero3.NP_damage
        team_obj.hero3.NP_charge = 0
    return total_damage

def calc_chain_damage(team_obj, card_chain, round_reward,servant_list):
    total_damage = 0
    first_card = card_chain[0]
    #print(first_card)
    dmg_modifier, np_mod, star_mod = first_card_mods(first_card)
    crit_mod = critical_role(team_obj)
    
    #Adding in NP charging from abilities
    charge_hero_np(team_obj,'hero1',team_obj.hero_dict['hero1'].NP_gain_buff)
    charge_hero_np(team_obj,'hero2',team_obj.hero_dict['hero2'].NP_gain_buff)
    charge_hero_np(team_obj,'hero3',team_obj.hero_dict['hero3'].NP_gain_buff)
    # zero out the np_gain_buffs
    team_obj.hero_dict['hero1'].NP_gain_buff = 0
    team_obj.hero_dict['hero2'].NP_gain_buff = 0
    team_obj.hero_dict['hero3'].NP_gain_buff = 0
    
    #using the NP should occur before card chain effects are calculated
    # player_team.hero_dict['hero2'].NP_gain_buff
    total_damage = use_NP(team_obj,total_damage)
    
    
    #arts and quick chain bonuses are executed in the 
    # card chain effect function
    #adding buster effect into the damage calculation    
    buster_chain_effect, round_reward = card_chain_effect(card_chain,team_obj,round_reward)
    
    for i in range(3):
        card = command_card_gen(card_chain[i],i+1)
        #star generation
        card_stars = card.stars*star_mod
        team_obj.current_stars += card_stars
        servant_damage_mod = get_hero_damage_mods(team_obj,card_chain[i],servant_list[i])
        #dmg 
        '''
        ADD IN DAMAGE MOD FROM SERVANT HERE SINCE WE GET TO THE CARD LEVEL
        '''
        card_dmg = card.dmg *dmg_modifier *buster_chain_effect*crit_mod * servant_damage_mod
        total_damage+= card_dmg
        
        #np
        card_np_gain = card.np_gain*np_mod
        charge_hero_np(team_obj,servant_list[i],card_np_gain)
        #team_obj.np_charge += card_np_gain #need a function to add to servant np
        
    if team_obj.hero1.NP_charge >= 100:
        round_reward +=1
    if team_obj.hero2.NP_charge >= 100:
        round_reward +=1
    if team_obj.hero3.NP_charge >= 100:
        round_reward +=1

    return total_damage, round_reward


## new stuff... how to add in damage buffs?????

adding buster arts and quick damage mods per servant

In [11]:
def apply_dmg_boost(team_obj, action_skill):
    targets = action_skill['target']
    
    if action_skill['dmg_boost'][0] == 'all':
        cards_to_mod = ['buster','arts','quick']
    else:
        cards_to_mod = action_skill['dmg_boost'][0]
    dmg_mod = action_skill['dmg_boost'][1]
    
    for i in targets:
        for key, item in team_obj.hero_dict[i].damage_mod_dict.items():
            print(key)
            if key in cards_to_mod:
                print(key)
                team_obj.hero_dict[i].damage_mod_dict[key] = team_obj.hero_dict[i].damage_mod_dict[key]+ team_obj.hero_dict[i].damage_mod_dict[key]*dmg_mod
                
def reset_hero_dmg_mods(team_obj,hero_number):
    for key, item in team_obj.hero_dict[hero_number].damage_mod_dict.items():
        team_obj.hero_dict[hero_number].damage_mod_dict[key] = 1

player_team = Chaldea()

apply_dmg_boost(player_team,player_team.hero1.skill_1())

buster
buster
arts
arts
quick
quick


# applying skills

Use the overarching Chaldea team dictionary to apply it to heroes??? 


In [12]:
'''
need to apply for every buff
'''

import copy
player_team = Chaldea()
        


def apply_buffs(team_obj, action_skill):
    targets = action_skill['target']
    hero1_buffs = copy.deepcopy(team_obj.hero_dict['hero1'].active_buffs_dict)
    hero2_buffs = copy.deepcopy(team_obj.hero_dict['hero2'].active_buffs_dict)
    hero3_buffs = copy.deepcopy(team_obj.hero_dict['hero3'].active_buffs_dict)
    #print(hero1_buffs,hero2_buffs,hero3_buffs)
    
    action_skill_copy = copy.deepcopy((copy.deepcopy(action_skill)))
    for target in targets:
        #print(target)
        if target == 'hero1':
            hero1_buffs[target+'_'+action_skill_copy['name']] = action_skill_copy
            team_obj.hero_dict['hero1'].active_buffs_dict = hero1_buffs
        elif target == 'hero2':
            hero2_buffs[target+'_'+action_skill_copy['name']] = action_skill_copy
            team_obj.hero_dict['hero2'].active_buffs_dict = hero2_buffs
        elif target == 'hero3':
            hero3_buffs[target+'_'+action_skill_copy['name']] = action_skill_copy
            team_obj.hero_dict['hero3'].active_buffs_dict = hero3_buffs
    
        
        
apply_buffs(player_team,player_team.hero1.skill_1())
apply_buffs(player_team,player_team.hero1.skill_2())

In [13]:
player_team.hero_dict['hero1'].active_buffs_dict

{'hero1_sk1_hero1_jalter_self_modification_ex': {'name': 'sk1_hero1_jalter_self_modification_ex',
  'target': ['hero1'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.5,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.0),
  'duration': 3},
 'hero1_sk2_hero1_jalter_dragon_witch': {'name': 'sk2_hero1_jalter_dragon_witch',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 3}}

In [14]:
player_team.hero_dict['hero2'].active_buffs_dict

{'hero2_sk2_hero1_jalter_dragon_witch': {'name': 'sk2_hero1_jalter_dragon_witch',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 3}}

In [15]:
player_team.hero_dict['hero3'].active_buffs_dict

{'hero3_sk2_hero1_jalter_dragon_witch': {'name': 'sk2_hero1_jalter_dragon_witch',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 3}}

In [16]:
# for every hero add up damage for each type of damage?
# then add that to the heroes damage modifier
def reset_hero_damage_mods(team_obj):
    cards_to_mod = ['buster','arts','quick']
    hero_list = ['hero1','hero2','hero3']
    for card_type in cards_to_mod:
        for hero in hero_list:               
            team_obj.hero_dict[hero].damage_mod_dict[card_type] = 1

# this is where I should track all the buffs getting applied
def increment_turns_for_buffs_gather_mods(team_obj):
    hero_list = ['hero1','hero2','hero3']
    hero_damage_mods_dict = {}
    #damage_mod_dict
    # reset new stuff before
    #print( team_obj.hero_dict['hero1'].damage_mod_dict)
    reset_hero_damage_mods(team_obj)
    #print( team_obj.hero_dict['hero1'].damage_mod_dict)
    hero1_dict_copy = copy.deepcopy(team_obj.hero_dict['hero1'].active_buffs_dict)
    hero2_dict_copy = copy.deepcopy(team_obj.hero_dict['hero2'].active_buffs_dict)
    hero3_dict_copy = copy.deepcopy(team_obj.hero_dict['hero3'].active_buffs_dict)
    
    hero_active_buff_copy_dict = {'hero1':hero1_dict_copy,'hero2':hero2_dict_copy,'hero3':hero3_dict_copy}
    
    hero1_dmg_dict_copy = copy.deepcopy(team_obj.hero_dict['hero1'].damage_mod_dict)
    hero2_dmg_dict_copy = copy.deepcopy(team_obj.hero_dict['hero2'].damage_mod_dict)
    hero3_dmg_dict_copy = copy.deepcopy(team_obj.hero_dict['hero3'].damage_mod_dict)
    
    hero_dmg_dict_copy_dict = {'hero1':hero1_dmg_dict_copy,
                               'hero2':hero2_dmg_dict_copy,
                               'hero3':hero3_dmg_dict_copy}
    #print(hero_dmg_dict_copy_dict)
    hero_dmg_hacky_index = 0

    for heros_buffs_key,heros_buffs_value in hero_active_buff_copy_dict.items():
        #print('wut',heros_buffs_value)
        for key, value in heros_buffs_value.items():
            #print(key,value)
            #value = copy.deepcopy(value)
            if value['duration'] > 0:
                
                ## accumulate NP boosts when looking at the things and store it somewhere
                if value['np_boost'] >0:
                     team_obj.hero_dict[heros_buffs_key].NP_gain_buff += value['np_boost']
                # Add in critical stars?
                if value['critical_star_boost'] >0: #this one gets added to then set to 0 during calc damage
                     team_obj.current_stars += value['critical_star_boost']
                        
                if value['critical_boost'] >0: #gets added at hero level... needs to gert zeroed
                    team_obj.critical_strength += value['critical_boost']

                ############
                if value['dmg_boost'][0] == 'all':
                    cards_to_mod = ['buster','arts','quick']
                else:
                    cards_to_mod = [value['dmg_boost'][0]]

                for card_type in cards_to_mod:
                    #for hero_dmg_dict in hero_dmg_dict_copy_list:
                    #print(card_type)
                    hero_dmg_dict_copy_dict[heros_buffs_key][card_type]+=value['dmg_boost'][1]
                    #hero1_dmg_dict_copy[card_type] +=value['dmg_boost'][1]
                    #hero2_dmg_dict_copy[card_type] +=value['dmg_boost'][1]
                    #hero3_dmg_dict_copy[card_type] +=value['dmg_boost'][1]
                        #hero_dmg_dict[card_type] += value['dmg_boost'][1]
                heros_buffs_value[key]['duration'] -= 1

    for i in list(hero1_dict_copy.keys()):
        if hero1_dict_copy[i]['duration'] <=0:
            del hero1_dict_copy[i]
    
    for i in list(hero2_dict_copy.keys()):
        if hero2_dict_copy[i]['duration'] <=0:
            del hero2_dict_copy[i]
    
    for i in list(hero3_dict_copy.keys()):
        if hero3_dict_copy[i]['duration'] <=0:
            del hero3_dict_copy[i]

    team_obj.hero_dict['hero1'].active_buffs_dict = hero1_dict_copy
    team_obj.hero_dict['hero2'].active_buffs_dict = hero2_dict_copy
    team_obj.hero_dict['hero3'].active_buffs_dict = hero3_dict_copy
    
    team_obj.hero_dict['hero1'].damage_mod_dict = hero1_dmg_dict_copy
    team_obj.hero_dict['hero2'].damage_mod_dict = hero2_dmg_dict_copy
    team_obj.hero_dict['hero3'].damage_mod_dict = hero3_dmg_dict_copy      

player_team = Chaldea()

apply_buffs(player_team,player_team.hero2.skill_2())               
apply_buffs(player_team,player_team.hero2.skill_1())

#increment_turns_for_buffs_gather_mods(player_team)    




In [17]:
#apply_buffs(player_team,player_team.hero2.skill_2())
increment_turns_for_buffs_gather_mods(player_team)    
player_team.hero_dict['hero2'].NP_gain_buff

50

In [18]:
player_team.hero_dict['hero2'].active_buffs_dict

{'hero2_sk1_hero2_Ishtar_manifestation_of_beauty': {'name': 'sk1_hero2_Ishtar_manifestation_of_beauty',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 2}}

In [19]:
player_team.hero_dict['hero2'].damage_mod_dict

{'buster': 1.2, 'arts': 1.2, 'quick': 1.2}

In [20]:
player_team.hero_dict['hero1'].damage_mod_dict

{'buster': 1.2, 'arts': 1.2, 'quick': 1.2}

In [21]:
player_team.hero_dict['hero2'].active_buffs_dict

{'hero2_sk1_hero2_Ishtar_manifestation_of_beauty': {'name': 'sk1_hero2_Ishtar_manifestation_of_beauty',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 2}}

In [22]:
player_team.hero_dict['hero3'].active_buffs_dict

{'hero3_sk1_hero2_Ishtar_manifestation_of_beauty': {'name': 'sk1_hero2_Ishtar_manifestation_of_beauty',
  'target': ['hero1', 'hero2', 'hero3'],
  'hp_boost': 0,
  'np_boost': 0.0,
  'critical_boost': 0.0,
  'critical_star_boost': 0.0,
  'dmg_boost': ('all', 0.2),
  'duration': 2}}

# crit star testing and critial strength testing

In [23]:
player_team = Chaldea()
apply_buffs(player_team,player_team.hero1.skill_1())               
apply_buffs(player_team,player_team.hero3.skill_3())               
increment_turns_for_buffs_gather_mods(player_team)    


In [24]:
player_team.critical_strength

0.5

In [25]:
player_team.current_stars

10

In [38]:

def get_buff_game_state(team_obj,return_dict = False):
    skill_dict = {'sk1_hero1':0,'sk2_hero1':0,'sk3_hero1':0,
                 'sk1_hero2':0,'sk2_hero2':0,'sk3_hero2':0,
                 'sk1_hero3':0,'sk2_hero3':0,'sk3_hero3':0}
    hero1_dict_copy = copy.deepcopy(team_obj.hero_dict['hero1'].active_buffs_dict)
    hero2_dict_copy = copy.deepcopy(team_obj.hero_dict['hero2'].active_buffs_dict)
    hero3_dict_copy = copy.deepcopy(team_obj.hero_dict['hero3'].active_buffs_dict)

    hero_active_buff_copy_dict = {'hero1':hero1_dict_copy,'hero2':hero2_dict_copy,'hero3':hero3_dict_copy}
    for heros_buffs_key,heros_buffs_value in hero_active_buff_copy_dict.items():
        if not heros_buffs_value: # check if empty
            continue
        else:
            for name, buff in heros_buffs_value.items():
                #print(name)
                skill_name = name.split('_')
                skill_dict[skill_name[1]+'_'+skill_name[2]] = 1

    active_buff_state = [skill_dict['sk1_hero1'],skill_dict['sk2_hero1'],skill_dict['sk3_hero1'],
                         skill_dict['sk1_hero2'],skill_dict['sk2_hero2'],skill_dict['sk3_hero2'],
                         skill_dict['sk1_hero3'],skill_dict['sk2_hero3'],skill_dict['sk3_hero3']]
    if return_dict == True:
        return active_buff_state,skill_dict

    return active_buff_state


def get_skill_use_game_state(team_obj):
    skill_use_list = []
    print(team_obj.hero_dict['hero1'].used_skill_1)
    skill_use_list.append(team_obj.hero_dict['hero1'].used_skill_1)
    skill_use_list.append(team_obj.hero_dict['hero1'].used_skill_2)
    skill_use_list.append(team_obj.hero_dict['hero1'].used_skill_3)
    
    skill_use_list.append(team_obj.hero_dict['hero2'].used_skill_1)
    skill_use_list.append(team_obj.hero_dict['hero2'].used_skill_2)
    skill_use_list.append(team_obj.hero_dict['hero2'].used_skill_3)
    
    skill_use_list.append(team_obj.hero_dict['hero3'].used_skill_1)
    skill_use_list.append(team_obj.hero_dict['hero3'].used_skill_2)
    skill_use_list.append(team_obj.hero_dict['hero3'].used_skill_3)
    
    return skill_use_list
    
def check_active_buffs_for_rewards(skill_dict):
    hero_list = ['hero1','hero2','hero3']
    skill_list = ['sk1','sk2','sk3']
    
    hero1_reward_bonus = 0
    hero2_reward_bonus = 0
    hero3_reward_bonus = 0
    
    for hero in hero_list:
        
        if hero == 'hero1':
            if skill_dict[hero+'_sk1'] == 1:
                hero1_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero1_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero1_reward_bonus = 2

        elif hero == 'hero2':
            if skill_dict[hero+'_sk1'] == 1:
                hero2_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero2_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero2_reward_bonus = 2
                
        elif hero == 'hero3':
            if skill_dict[hero+'_sk1'] == 1:
                hero3_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero3_reward_bonus = 2
            elif skill_dict[hero+'_sk3'] == 1:
                hero3_reward_bonus = 2
                
    return hero1_reward_bonus,hero2_reward_bonus,hero3_reward_bonus

In [27]:
turn = 0

#card types as classes
import itertools
from random import choice
from random import shuffle, randint
from utils import use_predicted_probability, convert_card_list

#player_team = team_chaldela() 
player_team = Chaldea()
player_team.card_deck = player_team.deck
win = 0 
loss = 0
turn_counter = 1
for game in range(3):
    print('')
    print('#'*50)
    print('ITS SHOW TIME! game: ',game)
    print('#'*50)
    print('reset enemies')
    if game == 0:
        enemy_team = enemy_servants(hp=30,dmg_max = 3)
    if game == 1:
        enemy_team = enemy_servants(hp=40,dmg_max = 4)
    if game == 2:
        enemy_team = enemy_servants(hp=60,dmg_max = 6)
    if check_if_alive(player_team) =='alive':
        while True:
            round_reward = 0 
            turn+=1
            enemy_dps = enemy_team.deal_damage()
            

            #### PLAYER TURN SECTION
            current_hand, servant_numbers = deal_hand(player_team.card_deck)
            #if self.evaluation ==True:
            #print('hand is: ',current_hand)
            #send list to the model
            
            #it should return an iterable? i think a tuple? of length 3 which correspond
            # to the card indicies
            print('#'*10,'hero1 damage mod dict Before','#'*10)
            print('hero1:',player_team.hero_dict['hero1'].damage_mod_dict)
            print('hero2:',player_team.hero_dict['hero2'].damage_mod_dict)
            print('hero3:',player_team.hero_dict['hero3'].damage_mod_dict)
            
            ### GET THOSE ACTIONS! ###
            # game state
            # do hero 1 actions and whatever
            hero1_state = [game]+[turn_counter]+get_buff_game_state(player_team)+get_skill_use_game_state(player_team)
            
            hero1_action = player_team.hero_dict['hero1'].get_action(hero1_state)
            print('hero1:',hero1_action)
            if hero1_action[0] != 'pass':
                hero1_reward = 1
                if game == 1:
                    hero1_reward +=.5:
                if game == 2:
                    hero1_reward +=1
                apply_buffs(player_team,hero1_action[1])
                if hero1_action[0] == 'sk1':
                    player_team.hero_dict['hero1'].used_skill_1 = 1
                elif hero1_action[0] == 'sk2':
                    player_team.hero_dict['hero1'].used_skill_2 = 1
                elif hero1_action[0] == 'sk3':
                    player_team.hero_dict['hero1'].used_skill_3 = 1

            print('game_state 1: game',game,'turn: ',turn_counter,'buffs',get_buff_game_state(player_team), get_skill_use_game_state(player_team))
            hero2_state = [game]+[turn_counter]+get_buff_game_state(player_team)+get_skill_use_game_state(player_team)
        
            hero2_action = player_team.hero_dict['hero2'].get_action(hero2_state)
            print('hero2:',hero2_action)

            if hero2_action[0] != 'pass':
                hero2_reward = 1
                if game == 1:
                    hero1_reward +=.5:
                if game == 2:
                    hero2_reward +=1
                apply_buffs(player_team,hero2_action[1])
                if hero2_action[0] == 'sk1':
                    player_team.hero_dict['hero2'].used_skill_1 = 1
                elif hero2_action[0] == 'sk2':
                    player_team.hero_dict['hero2'].used_skill_2 = 1
                elif hero2_action[0] == 'sk3':
                    player_team.hero_dict['hero2'].used_skill_3 = 1
            
            print('game_state 2: game',game,'turn: ',turn_counter,'buffs',get_buff_game_state(player_team), get_skill_use_game_state(player_team))
            hero3_state = [game]+[turn_counter]+get_buff_game_state(player_team)+get_skill_use_game_state(player_team)

            hero3_action = player_team.hero_dict['hero3'].get_action(hero3_state)
            print('hero3:',hero3_action)

            if hero3_action[0] != 'pass':
                hero3_reward = 1
                if game == 1:
                    hero1_reward +=.5:
                if game == 2:
                    hero3_reward +=1
                apply_buffs(player_team,hero3_action[1])
                if hero3_action[0] == 'sk1':
                    player_team.hero_dict['hero3'].used_skill_1 = 1
                elif hero3_action[0] == 'sk2':
                    player_team.hero_dict['hero3'].used_skill_2 = 1
                elif hero3_action[0] == 'sk3':
                    player_team.hero_dict['hero3'].used_skill_3 = 1
            
            print('game_state 3: game',game,'turn: ',turn_counter,'buffs',get_buff_game_state(player_team), get_skill_use_game_state(player_team))

            increment_turns_for_buffs_gather_mods(player_team)  
            print('#'*10,'hero1 damage mod dict after','#'*10)
            print('hero1:',player_team.hero_dict['hero1'].damage_mod_dict)
            print('hero2:',player_team.hero_dict['hero2'].damage_mod_dict)
            print('hero3:',player_team.hero_dict['hero3'].damage_mod_dict)
            print('#'*60)
            print('hero1 active buffs:',player_team.hero_dict['hero1'].active_buffs_dict)
            print('#'*60)
            print('hero2 active buffs:',player_team.hero_dict['hero2'].active_buffs_dict)
            print('#'*60)
            print('hero3 active buffs:',player_team.hero_dict['hero3'].active_buffs_dict)
            print('#'*60)
            #3 card tuple fed into pick_cards function which will generate the hand and start
            #dmg calculations
            converted_current_hand = convert_card_list(current_hand)
            card_picker_state = converted_current_hand+get_buff_game_state(player_team)#+get_skill_use_game_state(player_team)

            p1_action = player_team.card_picker.get_action(card_picker_state) #comment out for auto testing
            
            #p1_action = random_pick_cards() #testing pipeline
            print('game_state card picker: game',game,'turn: ',turn_counter,'buffs',get_buff_game_state(player_team), get_skill_use_game_state(player_team))

            picked_cards = pick_cards(current_hand,p1_action) #
            picked_servants = picked_cards_servants(servant_numbers,p1_action)

            print('cards to play: ',picked_cards, 'indexes: ', p1_action, 'servants: ',picked_servants)

            team_dps, round_reward = calc_chain_damage(player_team,picked_cards, round_reward, picked_servants)    

            print('team deals ',team_dps, ' current np bars: ', player_team.hero1.NP_charge,player_team.hero2.NP_charge,player_team.hero3.NP_charge, player_team.current_stars)
            print('enemy deals ',enemy_dps)

            player_team.hit_points -= enemy_dps
            enemy_team.hit_points -= team_dps
            
            
                        
            #check if player is still alive
            turn_counter += 1 #always keep incrementing the turn?
            
            if check_if_alive(player_team) =='alive' and check_if_alive(enemy_team) == 'dead':
                winner = 'player'
                win +=1
                round_reward+=1
                ## check active skills, gets bonus for having them active towards end of rounds?
                #skill_dict = {'sk1_hero1':0,'sk2_hero1':0,'sk3_hero1':0,
                ## 'sk1_hero2':0,'sk2_hero2':0,'sk3_hero2':0,
                # 'sk1_hero3':0,'sk2_hero3':0,'sk3_hero3':0}
                _, active_skill_dict = get_buff_game_state(player_team, return_dict = True)
                h1_bonus, h2_bonus, h3_bonus = check_active_buffs_for_rewards(active_skill_dict)
                print('game is a win')
                if game == 2: 
                    round_reward+=1
                #if self.evaluation == False:
                
                hero1_reward = round_reward
                hero2_reward = round_reward
                hero3_reward = round_reward
                        
                player_team.hero_dict['hero1'].update(hero1_state,hero1_reward)
                player_team.hero_dict['hero2'].update(hero2_state,hero2_reward)
                player_team.hero_dict['hero3'].update(hero3_state,hero3_reward)
                player_team.card_picker.update(card_picker_state,round_reward)

                #    player_team.update(current_hand,round_reward)

                break

            elif check_if_alive(player_team) =='dead':
                winner = 'enemy'
                loss +=1
                _, active_skill_dict = get_buff_game_state(player_team, return_dict = True)
                h1_bonus, h2_bonus, h3_bonus = check_active_buffs_for_rewards(active_skill_dict)
                print('game is a loss')
                round_reward= -2
                #if self.evaluation == False:
                #    player_team.update(current_hand,round_reward)
                hero1_reward += h1_bonus
                hero2_reward += h2_bonus
                hero3_reward += h3_bonus
                        
                player_team.hero_dict['hero1'].update(hero1_state,hero1_reward)
                player_team.hero_dict['hero2'].update(hero2_state,hero2_reward)
                player_team.hero_dict['hero3'].update(hero3_state,hero3_reward)
                player_team.card_picker.update(card_picker_state,round_reward)
                break
                
            #if self.evaluation == False:
                    #round_reward+=0
                    #player_team.update(current_hand,round_reward)
            hero1_reward = round_reward
            hero2_reward = round_reward
            hero3_reward = round_reward
                        
            player_team.hero_dict['hero1'].update(hero1_state,hero1_reward)
            player_team.hero_dict['hero2'].update(hero2_state,hero2_reward)
            player_team.hero_dict['hero3'].update(hero3_state,hero3_reward)
            player_team.card_picker.update(card_picker_state,round_reward)



##################################################
ITS SHOW TIME! game:  0
##################################################
reset enemies
[('hero2', 'arts'), ('hero3', 'buster'), ('hero2', 'buster'), ('hero1', 'buster'), ('hero3', 'buster')]
########## hero1 damage mod dict Before ##########
hero1: {'buster': 1, 'arts': 1, 'quick': 1}
hero2: {'buster': 1, 'arts': 1, 'quick': 1}
hero3: {'buster': 1, 'arts': 1, 'quick': 1}
0
[[-0.0072004   0.03083158  0.00996884  0.05127397]]
[[-0.0072004   0.03083158  0.00996884  0.05127397]]
hero1: ('pass', 'pass')
0
game_state 1: game 0 turn:  1 buffs [0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0]
0
[[ 0.00857216 -0.07819213  0.06328665  0.0542398 ]]
[[ 0.00857216 -0.07819213  0.06328665  0.0542398 ]]
hero2: ('pass', 'pass')
0
game_state 2: game 0 turn:  1 buffs [0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0]
0
[[-0.05429351  0.00494749  0.03849427 -0.10499717]]
[[-0.05429351  0.00494749  0.03849427 -0.10499717]]
hero3: ('sk2', {'n

### need to add cooldowns now that we can see classes 

can basically track if a skill has been selected... and remove it from the random actions??? who knows... probably good tracking for when the bot gets added?


# How the F do we start adding networks in?

The card picking network can do its thing as it is above

the network for the 3 heroic spirits... option 1 takes in 1 set of game states and each of them makes actions independently of one another... option 2. we do the thing in order so we have the most "selfish" or most DPS-y of them go last... which lets that character make decisions after the other two have potentially cast buffs... order is contrived but could be reasonable.... 

basically

- cards are picked based on game state (can be whenever, or maybe last based on if we add in context of when it has been buffed (and additional array of length 9?))
- support hero1
- support or off DPS (the DPS with more team buffs, artoria or ishtar?)
- greediest DPS (single target NP or one who mostly just has self buffs?)

In [28]:
print('hero1 active buffs:',player_team.hero_dict['hero1'].active_buffs_dict)
print('#'*60)
print('hero2 active buffs:',player_team.hero_dict['hero2'].active_buffs_dict)
print('#'*60)
print('hero3 active buffs:',player_team.hero_dict['hero3'].active_buffs_dict)
print('#'*60)

hero1 active buffs: {}
############################################################
hero2 active buffs: {}
############################################################
hero3 active buffs: {}
############################################################


In [29]:
#CAN USE THIS TO GET THE BUFF STATE AT ANY POINT TO AMKE THE GAME STATE


In [30]:
hero_active_buff_copy_dict = {'hero1':{},'hero2':{"a":2,'b':10},'hero3':{'w':3}}
for heros_buffs_key,heros_buffs_value in hero_active_buff_copy_dict.items():
    print(not heros_buffs_value)


True
False
False


In [31]:
hero3_action = player_team.hero_dict['hero3'].get_action(hero3_state)
hero3_action

[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]


('pass', 'pass')

In [32]:
for i in range(20):
    print( player_team.hero_dict['hero3'].get_action(hero3_state))

[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]
('pass', 'pass')
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -8.263278  -8.263278  -8.263278 ]]


In [33]:
player_team.hero_dict['hero3'].used_skill_1 = 0
player_team.hero_dict['hero3'].used_skill_2 = 0
player_team.hero_dict['hero3'].used_skill_3 = 0

In [34]:
for i in range(20):
    print( player_team.hero_dict['hero3'].get_action(hero3_state))

[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
('sk2', {'name': 'sk2_hero3_artoria_pendragon_mana_burst_b', 'target': ['hero3'], 'hp_boost': 0, 'np_boost': 0.0, 'critical_boost': 0.0, 'critical_star_boost': 0.0, 'dmg_boost': ('buster', 0.5), 'duration': 1})
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
('sk3', {'name': 'sk3_hero3_artoria_pendragon_instinct_a', 'target': ['hero3'], 'hp_boost': 0, 'np_boost': 0.0, 'critical_boost': 0.0, 'critical_star_boost': 10, 'dmg_boost': ('all', 0), 'duration': 1})
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
('sk1', {'name': 'sk1_hero3_artoria_pendragon_charisma_B', 'target': ['hero1', 'hero2', 'hero3'], 'hp_boost': 0, 'np_boost': 0.0, 'critical_boost': 0.0, 'critical_star_boost': 0, 'dmg_boost': ('all', 0.18), 'duration': 3})
[[-1.3854039 -5.334827  -7.263278  -4.0574303]]
[[-1.3854039 -5.334827  -7.

In [35]:


def invalid_steps(self,preds,level_valid_list,prev_top_cats=None):
    sk1_used = self.used_skill_1
    sk2_used = self.used_skill_2
    sk3_used = self.used_skill_3
    
    new_pred_min = np.min(preds[0])-1
    print(new_pred_min)
    for _index in range(len(self.action_dict)):
        _found=0
        if 'sk1' in self.action_dict[_index] and sk1_used == 1:
            preds[0][_index] = np.min(preds[pred_cords][0])-1
        if 'sk2' in self.action_dict[_index] and sk2_used == 1:
            preds[0][_index] = np.min(preds[pred_cords][0])-1
        if 'sk3' in self.action_dict[_index] and sk3_used == 1:
            preds[0][_index] = np.min(preds[pred_cords][0])-1
            
    #return _level_max, contains_top_level_list,_level_max_index


In [36]:
#skill_dict = {'sk1_hero1':0,'sk2_hero1':0,'sk3_hero1':0,
                ## 'sk1_hero2':0,'sk2_hero2':0,'sk3_hero2':0,
                # 'sk1_hero3':0,'sk2_hero3':0,'sk3_hero3':0}
#                _, active_skill_dict = get_buff_game_state(player_team, return_dict = True)
# feed in skill dict and have it check everything  
def check_active_buffs_for_rewards(skill_dict):
    hero_list = ['hero1','hero2','hero3']
    skill_list = ['sk1','sk2','sk3']
    
    hero1_reward_bonus = 0
    hero2_reward_bonus = 0
    hero3_reward_bonus = 0
    
    for hero in hero_list:
        
        if hero == 'hero1':
            if skill_dict[hero+'_sk1'] == 1
                hero1_reward_bonus = 1
            elif skill_dict[hero+'_sk3'] == 1
                hero1_reward_bonus = 1
            
            elif skill_dict[hero+'_sk3'] == 1
                hero1_reward_bonus = 1
        elif hero == 'hero2':
            if skill_dict[hero+'_sk1'] == 1
                hero2_reward_bonus = 1
            elif skill_dict[hero+'_sk3'] == 1
                hero2_reward_bonus = 1
            
            elif skill_dict[hero+'_sk3'] == 1
                hero2_reward_bonus = 1
                
        elif hero == 'hero3':
            if skill_dict[hero+'_sk1'] == 1
                hero3_reward_bonus = 1
            elif skill_dict[hero+'_sk3'] == 1
                hero3_reward_bonus = 1
            
            elif skill_dict[hero+'_sk3'] == 1
                hero3_reward_bonus = 1
                
    return hero1_reward_bonus,hero2_reward_bonus,hero3_reward_bonus

{}